# Generated by Django 4.1.7 on 2023-03-30 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=250)),
                ('cat_image', models.ImageField(upload_to='product_details/media/cat_images')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=250)),
                ('p_image', models.ImageField(upload_to='product_details/media/product_images')),
                ('p_brand', models.CharField(max_length=250)),
                ('p_status', models.SmallIntegerField()),
                ('p_des', models.TextField(max_length=5000)),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disc_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.SmallIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_details.category')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('w_id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_details.product')),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('v_id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=250)),
                ('color', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_details.product')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=250)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_details.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_details.subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='user_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
