# Generated by Django 4.1.7 on 2023-04-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0002_compareproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(upload_to='media/cat_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_image',
            field=models.ImageField(upload_to='media/product_images'),
        ),
    ]
