# Generated by Django 4.1.7 on 2023-07-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0005_mobilephones_lcd_laptops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lcd',
            name='category',
        ),
        migrations.RemoveField(
            model_name='lcd',
            name='product',
        ),
        migrations.RemoveField(
            model_name='lcd',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='mobilephones',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mobilephones',
            name='product',
        ),
        migrations.RemoveField(
            model_name='mobilephones',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='Laptops',
        ),
        migrations.DeleteModel(
            name='LCD',
        ),
        migrations.DeleteModel(
            name='MobilePhones',
        ),
    ]
