# Generated by Django 3.1.3 on 2023-07-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0007_mobilephones_lcd_laptops_ac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ac',
            name='energy_efficiency',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ac',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ac',
            name='warranty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='laptops',
            name='generation',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='laptops',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lcd',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mobilephones',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
