# Generated by Django 4.2.4 on 2023-08-17 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0009_alter_ac_id_alter_laptops_id_alter_lcd_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ac',
            old_name='capacity',
            new_name='ac_capacity',
        ),
        migrations.RenameField(
            model_name='ac',
            old_name='energy_efficiency',
            new_name='ac_energy_efficiency',
        ),
        migrations.RenameField(
            model_name='ac',
            old_name='inverter',
            new_name='ac_inverter',
        ),
        migrations.RenameField(
            model_name='ac',
            old_name='type',
            new_name='ac_type',
        ),
        migrations.RenameField(
            model_name='ac',
            old_name='warranty',
            new_name='ac_warranty',
        ),
        migrations.RenameField(
            model_name='laptops',
            old_name='battery',
            new_name='laptop_battery',
        ),
        migrations.RenameField(
            model_name='laptops',
            old_name='display',
            new_name='laptop_display',
        ),
        migrations.RenameField(
            model_name='laptops',
            old_name='generation',
            new_name='laptop_generation',
        ),
        migrations.RenameField(
            model_name='laptops',
            old_name='memory',
            new_name='laptop_memory',
        ),
        migrations.RenameField(
            model_name='laptops',
            old_name='processor',
            new_name='laptop_processor',
        ),
        migrations.RenameField(
            model_name='lcd',
            old_name='audio',
            new_name='lcd_audio',
        ),
        migrations.RenameField(
            model_name='lcd',
            old_name='chip',
            new_name='lcd_chip',
        ),
        migrations.RenameField(
            model_name='lcd',
            old_name='display',
            new_name='lcd_display',
        ),
        migrations.RenameField(
            model_name='lcd',
            old_name='power_consumption',
            new_name='lcd_power_consumption',
        ),
        migrations.RenameField(
            model_name='mobilephones',
            old_name='battery',
            new_name='mobile_battery',
        ),
        migrations.RenameField(
            model_name='mobilephones',
            old_name='camera',
            new_name='mobile_camera',
        ),
        migrations.RenameField(
            model_name='mobilephones',
            old_name='display',
            new_name='mobile_display',
        ),
        migrations.RenameField(
            model_name='mobilephones',
            old_name='processor',
            new_name='mobile_processor',
        ),
    ]
