# Generated by Django 4.2.4 on 2023-08-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0010_rename_capacity_ac_ac_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='size',
        ),
    ]
