# Generated by Django 4.2.4 on 2023-08-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0011_remove_variation_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(default='No Category', max_length=250),
        ),
    ]
