# Generated by Django 4.2.4 on 2023-08-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0012_alter_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ac',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='laptops',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='lcd',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='mobilephones',
            name='sub_category',
        ),
    ]
