# Generated by Django 4.2.4 on 2023-08-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0013_remove_ac_sub_category_remove_laptops_sub_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobilephones',
            old_name='memory',
            new_name='mobile_memory',
        ),
    ]
