# Generated by Django 4.1.7 on 2023-10-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0016_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
