# Generated by Django 4.1.7 on 2023-11-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0017_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='stars',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
