# Generated by Django 4.1.7 on 2023-11-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0018_alter_feedback_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
