# Generated by Django 4.2.4 on 2023-09-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='code',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
