# Generated by Django 4.2.4 on 2023-09-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0003_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='code',
        ),
    ]
