# Generated by Django 4.1.11 on 2023-10-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0004_remove_userdetails_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='verified',
            field=models.SmallIntegerField(default=1),
        ),
    ]
