# Generated by Django 4.1.7 on 2023-10-29 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0005_userdetails_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='phone_no',
            field=models.CharField(default=None, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{8,15}$')]),
        ),
    ]
