# Generated by Django 4.1.7 on 2023-10-29 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0007_alter_userdetails_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='phone_no',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{8,15}$')]),
        ),
    ]
