# Generated by Django 3.1.3 on 2023-08-03 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0005_auto_20230803_1945'),
        ('transaction_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='order_details.order'),
        ),
    ]
