# Generated by Django 4.1.7 on 2023-03-31 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_details', '0001_initial'),
        ('transaction_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(max_length=200)),
                ('total_bill', models.CharField(max_length=200)),
                ('bill_payed', models.CharField(max_length=200)),
                ('discount', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction_details.transaction')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentDetails',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=1000)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('od_id', models.AutoField(primary_key=True, serialize=False)),
                ('actual_price', models.CharField(max_length=200)),
                ('sale_price', models.CharField(max_length=200)),
                ('discount', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_details.order')),
                ('variation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_details.variation')),
            ],
        ),
    ]
