# Generated by Django 3.1.3 on 2023-07-21 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShipmentDetails',
        ),
    ]
