# Generated by Django 3.1.3 on 2023-07-21 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_details', '0002_delete_shipmentdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentDetails',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=1000)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
