# Generated by Django 3.1.3 on 2023-08-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0003_shipmentdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentdetails',
            name='address',
            field=models.CharField(max_length=1000),
        ),
    ]
