# Generated by Django 3.1.3 on 2023-08-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0004_auto_20230802_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
