# Generated by Django 4.2.4 on 2023-09-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0007_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='o_panel',
            field=models.IntegerField(default=1),
        ),
    ]
