# Generated by Django 4.2.4 on 2023-09-11 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0008_order_o_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentdetails',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order_details.order'),
            preserve_default=False,
        ),
    ]
